spring:
  mail:
    default-encoding: UTF-8
    # 设置邮箱主机
    host: smtp.qq.com
    # 用户名
    username: 1107438082@qq.com
    # 密码
    password: mdbnixrxthqrgeea
    #  邮件服务器名称,例如:POP3、SMTP、IMAP每个服务器对应端口不一样
    protocol: smtp
    # 端口
    port: 465
    properties:
      mial:
        smtp:
        # 设置是否需要认证，如果为true,那么用户名和密码就必须的，
        # 如果设置false，可以不设置用户名和密码，当然也得看你的对接的平台是否支持无密码进行访问的。
          auth: true
          starttls:
            enable: true
            required: true
          # 超时时间
          timeout: 25000