spring:
  mail:
    default-encoding: UTF-8
    # 设置邮箱主机
    host: smtp.126.com
    # 用户名
    username: weiqiang_6@126.com
    # 密码
    password: XYLWQHAN311525
    #  邮件服务器名称,例如:POP3、SMTP、IMAP每个服务器对应端口不一样
    protocol: smtp
    # 端口
#    port: 25
    properties:
      mial:
        smtp:
        # 设置是否需要认证，如果为true,那么用户名和密码就必须的，
        # 如果设置false，可以不设置用户名和密码，当然也得看你的对接的平台是否支持无密码进行访问的。
          auth: true
          # 超时时间
          timeout: 25000


# 阿里云短信配置 注意替换自己申请的配置
aliyun:
  sms:
    accessKey: LTAI3LujUtvtrExX
    accessKeySecret: aYz8a9dXoCMeK6OFejqGsGH164783x
    sign:
      name: 大数据报告
    template:
      code: SMS_134195068